### ISSUE TITLE
Hi does the image has the correct torch version?

### ISSUE THREAD

**Issue by moyutianque** [YanyuanQiao/HOP-REVERIE-Challenge#1]
I found the version of pytorch is 1.1.0. and running test.bash will raise 
`AttributeError: module 'torch.optim' has no attribute 'AdamW'`

I use singularity to run the image, but I guess this does not matter too much.

The python I used in the image is 
`/miniconda/envs/py37/bin/python`

**Comment by YanyuanQiao** [comment]
> I found the version of pytorch is 1.1.0. and running test.bash will raise `AttributeError: module 'torch.optim' has no attribute 'AdamW'`
> 
> I use singularity to run the image, but I guess this does not matter too much.
> 
> The python I used in the image is `/miniconda/envs/py37/bin/python`

I will check it later, you can use pytorch = 1.4.0.
